services :
  
  postgres:
  container_name: coffee_postgres
    image: postgres:13
    environment:
      POSTGRES_DB: coffee_shop_db
      POSTGRES_USER: coffee_user
      POSTGRES_PASSWORD: Happy.Coffee:Shop*007! 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 

volumes:
  postgres_data:
