# Generated by Django 6.0.1 on 2026-01-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
