# Generated by Django 6.0.1 on 2026-01-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Product Name')),
                ('description', models.TextField(max_length=255, verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Product Price')),
                ('stock', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('product_image', models.URLField(blank=True, null=True, verbose_name='Product Image')),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('category', models.CharField(max_length=32, verbose_name='Product Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
